/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_dict.ui;

import oop_dict.server.Dictionary;
import oop_dict.server.TranslatorAPI;
import oop_dict.server.TextToSpeech;
import oop_dict.server.Trie;
import org.jsoup.Jsoup;

import static oop_dict.server.TranslatorAPI.*;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Objects;
import java.util.Optional;
import javax.swing.JScrollPane;
import javax.swing.JEditorPane;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;

/**
 *
 * @author hungh
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();

        try {
            initialize();
        }
        catch (SQLException e){
            e.printStackTrace();
        }
    }

    public static String escape(String s) {
        StringBuilder builder = new StringBuilder();
        boolean previousWasASpace = false;
        for( char c : s.toCharArray() ) {
            if( c == ' ' ) {
                if( previousWasASpace ) {
                    builder.append("&nbsp;");
                    previousWasASpace = false;
                    continue;
                }
                previousWasASpace = true;
            } else {
                previousWasASpace = false;
            }
            switch(c) {
                case '<': builder.append("&lt;"); break;
                case '>': builder.append("&gt;"); break;
                case '&': builder.append("&amp;"); break;
                case '"': builder.append("&quot;"); break;
                case '\n': builder.append("<br>"); break;
                // We need Tab support here, because we print StackTraces as HTML
                case '\t': builder.append("&nbsp; &nbsp; &nbsp;"); break;
                default:
                    if( c < 128 ) {
                        builder.append(c);
                    } else {
                        builder.append("&#").append((int)c).append(";");
                    }
            }
        }
        return builder.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        HomeButton = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().setLayout(null);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(170, 150, 240, 41);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 255));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTextField2.setText("Your word here:");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(170, 110, 240, 41);

        jList1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "item 6", "item 7", "item 8", "item 9", "item 10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 190, 240, 400);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 153, 255));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTextField3.setText("Meaning");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(410, 110, 350, 40);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(102, 255, 102));
        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTextField4.setText("ENGLISH TO VIETNAMESE");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(760, 110, 290, 40);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(760, 150, 290, 440);

        HomeButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        HomeButton.setText("HOME");
        HomeButton.setMaximumSize(new java.awt.Dimension(100, 100));
        HomeButton.setMinimumSize(new java.awt.Dimension(100, 100));
        HomeButton.setPreferredSize(new java.awt.Dimension(100, 100));
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(HomeButton);
        HomeButton.setBounds(0, 0, 110, 100);

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField5.setText("");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(180, 690, 170, 50);

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField6.setText("");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(390, 690, 340, 50);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(102, 204, 255));
        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField7.setText("Từ:");
        getContentPane().add(jTextField7);
        jTextField7.setBounds(180, 640, 170, 40);

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(153, 255, 102));
        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField8.setText("Định nghĩa:");
        getContentPane().add(jTextField8);
        jTextField8.setBounds(390, 640, 340, 40);

        jButton1.setText("Thêm từ vào Database");
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 760, 170, 40);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                System.out.println(jTextField5.getText());
                dictionary.addWord(jTextField5.getText(), jTextField6.getText());
            }
        });

        jButton2.setText("Phát âm từ (EN)");
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 150, 150, 40);

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextToSpeech.playSoundGoogleTranslate(jTextField1.getText(), "en");
            }
        });

        jButton3.setText("Xóa từ khỏi Database");
        getContentPane().add(jButton3);
        jButton3.setBounds(390, 760, 170, 40);

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dictionary.deleteWord(jTextField5.getText());
            }
        });

//        jTextArea1.setColumns(20);
//        jTextArea1.setRows(5);
        HTMLEditorKit kit = new HTMLEditorKit();
        jTextArea1.setEditorKit(kit);
        jTextArea1.setEditable(false);
        jScrollPane4.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(410, 150, 350, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initialize() throws SQLException {
        dictionary = new Dictionary();
        try {
            dictionary.init();
        } catch (SQLException e){
            e.printStackTrace();
        }
        this.add(jScrollPane4);
        HomeButton.setSize(100,100);
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "NULL" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
    }

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText() != ""){
            String target = jTextField1.getText();
            ArrayList<String> searchedWords = Trie.search(target);
            jList1.setModel(new javax.swing.AbstractListModel<String>() {
                ArrayList<String> strings = searchedWords;
                public int getSize() { return searchedWords.size(); }
                public String getElementAt(int i) { return strings.get(i); }
            });

            String definition = dictionary.findWord(target);
//            System.out.println(definition);
            jTextArea1.setText(definition);
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            jTextArea2.setText(translateEnToVi(jTextField1.getText()));
        }

        if (evt.getKeyChar() == '\n'){
            String target = jTextField1.getText();
            ArrayList<String> searchedWords = Trie.search(target);

            jList1.setModel(new javax.swing.AbstractListModel<String>() {
                ArrayList<String> strings = searchedWords;
                public int getSize() { return searchedWords.size(); }
                public String getElementAt(int i) { return strings.get(i); }
            });

            String definition = dictionary.findWord(target);
//            System.out.println(definition);
            jTextArea1.setText(definition);
        }

    }//GEN-LAST:event_jTextField1KeyPressed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        if (jList1.getSelectedValue() != "NULL") {
            jTextField1.setText(jList1.getSelectedValue());
            String target = jTextField1.getText();

            String definition = dictionary.findWord(target);
//            System.out.println(definition);
            jTextArea2.setText("");
            jTextArea1.setText(definition);
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            jTextArea2.setText(translateEnToVi(jTextField1.getText()));
        }
    }//GEN-LAST:event_jList1KeyPressed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton HomeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JEditorPane jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JEditorPane jEditorPane1;
    // End of variables declaration//GEN-END:variables
    private Dictionary dictionary;
}
